[package]
name = "shuftlib"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
rand="0.8"
strum = {version="0.25", default-features=false, features=["derive"]}

[dev-dependencies]

[lints]
workspace = true
